NUMPY START

In [2]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [6]:
b=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [9]:
a.ndim #for dimension

1

In [10]:
b.ndim

2

In [11]:
a.shape #shape

(6,)

In [12]:
b.shape

(2, 6)

In [13]:
a.dtype

dtype('int64')

In [14]:
a.size # no of element

6

In [15]:
a.size*a.itemsize # total space occupied

48

### Accesing and changing elements,rows,columns,etc

In [3]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [5]:
print(a[1,-2])

13


In [9]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
a[:,2]

array([ 3, 10])

In [11]:
a[0,1:-1:2]

array([2, 4, 6])

In [12]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [14]:
a[:,2]=5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


### 3-D examples

In [17]:
b=np.array([[[1,2],[3,4]],[[5,6,],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [19]:
print(b[1,0,0])

5


In [20]:
b[:,1,1]=9
print(b)

[[[1 2]
  [3 9]]

 [[5 6]
  [7 9]]]


In [21]:
b[:,1,:]=[[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### different types of arrays

In [23]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [26]:
np.full((2,3),99)

array([[99, 99, 99],
       [99, 99, 99]])

In [28]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [29]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [30]:
np.random.rand(2,4)

array([[0.7109917 , 0.49219088, 0.04012957, 0.11103025],
       [0.8313859 , 0.6335884 , 0.45844652, 0.15553507]])

In [31]:
np.random.sample(a.shape)

array([[0.75364136, 0.32014946, 0.61303054, 0.58168361, 0.83418835,
        0.37857147, 0.6978129 ],
       [0.61166207, 0.41845469, 0.57163179, 0.26208804, 0.01452488,
        0.45678916, 0.04403506]])

In [34]:
np.random.randint(4,8,size=(2,4))

array([[4, 6, 4, 4],
       [5, 5, 5, 5]], dtype=int32)

In [35]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## repeat values

In [45]:
arr=np.array([1,2,3])
r1=np.repeat(arr,3,axis=0)#(arr,time,axis) 0=column and 1=rows
print(r1)

[1 1 1 2 2 2 3 3 3]


In [43]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [46]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


## copy

In [48]:
a=np.array([1,2,3])
b=a
b[1]=5
print(b)
print(a) # both change so don't do it

[1 5 3]
[1 5 3]


In [49]:
a=np.array([1,2,3])
b=a.copy()
b[1]=5
print(b)
print(a) # didn't change do this

[1 5 3]
[1 2 3]


### Mathamatics

In [50]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [51]:
a+2

array([3, 4, 5, 6])

In [52]:
a-2

array([-1,  0,  1,  2])

In [53]:
a*2

array([2, 4, 6, 8])

In [55]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [56]:
a**2

array([ 1,  4,  9, 16])

In [58]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [59]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [61]:
np.sin(a)# and more trig. function

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

## Linear algebra

In [63]:
a=np.ones((2,3))
b=np.full((3,2),2)
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [65]:
c=np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [66]:
stats=np.array([[1,2],[3,4]])
stats

array([[1, 2],
       [3, 4]])

In [67]:
np.min(stats)

np.int64(1)

In [68]:
np.min(stats,axis=0)

array([1, 2])

In [69]:
np.max(stats)

np.int64(4)

In [72]:
np.max(stats,axis=1)

array([2, 4])

In [73]:
np.sum(stats,axis=1)

array([3, 7])

### Reorganizing Arrays

In [75]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [80]:
after=before.reshape((4,2))
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [86]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack((v1,v2,v2,v1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [87]:
h1=np.array([1,2,3,4])
h2=np.array([5,6,7,8])
np.hstack((h1,h2))

array([1, 2, 3, 4, 5, 6, 7, 8])

### load data from a file

In [93]:
filedata=np.genfromtxt('https://raw.githubusercontent.com/KeithGalli/NumPy/refs/heads/master/data.txt',delimiter=',')
filedata=filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

In [94]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [95]:
np.any(filedata>50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [96]:
np.all(filedata>50,axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [98]:
((filedata>50)&(filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [99]:
~((filedata>50)&(filedata<100))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])